# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Bongloy_Example' do
  pod 'Bongloy', :path => '../'

  use_frameworks!

  pod 'Alamofire'
  pod 'CreditCardForm'
  pod 'SCLAlertView'

  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end
end
